version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1000
    labels:
      - "dependencies"
      - "npm"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 1000
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "docker"
    directory: "/docker/complete"
    schedule:
      interval: daily
      time: '05:00'
    open-pull-requests-limit: 1000
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: '06:00'
    open-pull-requests-limit: 1000
    labels:
      - "dependencies"
      - "laravel-composer"
